services:
  inventarius-prod:
    image: inventarius-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: inventarius-prod
    volumes:
      - ./public:/app/public
      - ./logs:/app/logs
      - ./nodemon.json:/app/nodemon.json
      - .env:/app/.env
    environment:
      PORT: ${DOCKER_PORT}
      MONGO_URL: ${DOCKER_MONGO_URL}
      MONGO_DBNAME: ${DOCKER_MONGO_DBNAME}
      DB_HOST: ${DOCKER_DB_HOST}
      DB_DATABASE: ${DOCKER_DB_DATABASE}
      DB_USERNAME: ${DOCKER_DB_USERNAME}
      DB_PASSWORD: ${DOCKER_DB_PASSWORD}
      DB_DIALECT: ${DOCKER_DB_DIALECT}
      NODE_ENV: production
      DEBUG: false
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    command: npm run prod